### ISSUE TITLE
GUI Enhancements

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/igb-geonode#20]
or a final check I went through our description of work again, and I noticed that one small point that has not been tackled so far: 
* include web links to IGB and FRED (https://fred.igb-berlin.de/) websites with logos at the bottom of the front page

We would be very happy if you could still include the two links and logos in the custom IGB project, as we want to show that GeoNode is meant to be connected to the IGB website and the FRED database (and will be in the future I hope). FRED does not have a logo though, there we would just need the title "IGB Freshwater Research and Environmental Database" and the link; the title for IGB would be "Leibniz-Institute of Freshwater Ecology and Inland Fisheries". Logo and Links can be found in the shared space: https://nimbus.igb-berlin.de/index.php/s/otd88B9gwj8pSoR (password: igb_geo)!

**Comment by afabiani** [comment]
We currently updated the geonode-template **footer** as follows

![image](https://user-images.githubusercontent.com/1278021/66484023-76cb0c80-eaa6-11e9-8bd5-82b4f56e558c.png)

Source code currently available here

https://github.com/geosolutions-it/igb-geonode.git
