### ISSUE TITLE
LDAP Configuration docs

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/igb-geonode#21]
We would like to ask you though if you could provide a short, basic documentation of the LDAP settings you used? As I understood this was quite complex to figure out, so it would be important to us to have a short description of the applied configuration.

**Comment by afabiani** [comment]
Link to the Google Doc: https://docs.google.com/document/d/1Kh_VD5OvehHzYe3BMjMVfwfH3vA7FixM1VdNt7bG-d0/edit?usp=sharing
