### ISSUE TITLE
List of all registered ADMIN

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/igb-geonode#22]
Also could you please provide us with a list of all registered ADMIN users (with username and password), that currently have admin status on the production and development sites and also the GeoServer admin user (preferably in a document in the shared space, not per e-mail).

**Comment by afabiani** [comment]
Link to the Google Doc: https://docs.google.com/document/d/1Kh_VD5OvehHzYe3BMjMVfwfH3vA7FixM1VdNt7bG-d0/edit?usp=sharing
