### ISSUE TITLE
L&F Customization

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/igb-geonode#6]
- [ ] integrate the IGB logo as well as the new name for the system (to be defined) in the header section
- [ ] adapt the front page text block
- [ ] implement a color scheme based on the IGB website (https://www.igb-berlin.de/en)
- [ ] include web links to IGB and FRED websites with logos at the bottom of the front page

**Comment by ricardogsilva** [comment]
@simboss 

Please share the link to where the look&feel materials supplied by the client is placed

**Comment by simboss** [comment]
@ricardogsilva you can find all they gave me in [this](https://www.dropbox.com/sh/rg0xvlijgomeahs/AAAY18ReeFpjXvpu_1cXRNlta?dl=0) dropbox folder.

As I said, let's do something simple and stay within the original estimate which you should have access to.

If there's anything, let me know.

**Comment by ricardogsilva** [comment]
@simboss 
I've pushed my simple customization of L&F and updated test server accordingly.

In all, spent ~1.5 day with this.

IMO it is not too fancy, but works
